<a href="https://colab.research.google.com/github/Yevheniia-Ilchenko/ML_DS_tasks/blob/main/HW_2_1_%D0%9C%D0%B0%D1%82%D1%80%D0%B8%D1%86%D1%96_%D1%96_%D0%B2%D0%B5%D0%BA%D1%82%D0%BE%D1%80%D0%B8_(%D0%B2%D1%81%D1%82%D1%83%D0%BF_%D0%B4%D0%BE_%D0%BB%D1%96%D0%BD_%D0%B0%D0%BB%D0%B3%D0%B5%D0%B1%D1%80%D0%B8).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [3]:
import numpy as np

In [28]:
vector = np.random.rand(10)
print(vector)

[0.69480758 0.10481843 0.9960692  0.83733147 0.50785093 0.89413873
 0.87886018 0.74508175 0.48928488 0.54766891]


In [7]:
vector.shape

(10,)

In [29]:
matrix = np.array([[11, 14, 17], [20, 23, 26], [29, 32, 35]])
print(matrix)

[[11 14 17]
 [20 23 26]
 [29 32 35]]


In [9]:
matrix.shape

(3, 3)


### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [21]:
vector_10 = (vector + 10).round(2)
print(vector_10)

[10.6  10.77 10.65 10.22 10.06 10.06 10.03 10.69 10.53 10.75]


In [22]:
vector_2 = vector * 2
print(vector_2)

[1.20577482 1.53899975 1.29839239 0.44309415 0.12955462 0.12599376
 0.06442782 1.37460594 1.05559886 1.4931248 ]


In [23]:
vector_square = vector **2
print(vector_square)

[0.36347323 0.59213006 0.4214557  0.04908311 0.0041961  0.00396861
 0.00103774 0.47238537 0.27857224 0.55735542]



### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [5]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

Перший варіант множення щоб отримати 2х2

In [12]:
result_matrix = np.dot(B, A)
print(result_matrix)

[[0.7281 0.5202]
 [0.2034 0.2846]]


Другий варіант множення щоб отримати 2х2

In [13]:
result_matrix_2 = np.dot(A.T,B.T)
print(result_matrix_2)

[[0.7281 0.2034]
 [0.5202 0.2846]]


In [14]:
result_matrix_C = np.dot(result_matrix, C)
print(result_matrix_C)

[[0.5202]
 [0.2846]]


In [15]:
result_matrix_D = np.dot(result_matrix, D)
print(result_matrix_D)

[[0.5202 0.7281]
 [0.2846 0.2034]]



### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [16]:
result_matrix.T

array([[0.7281, 0.2034],
       [0.5202, 0.2846]])

In [39]:
vector.shape

(10,)

In [36]:
vector

array([0.69480758, 0.10481843, 0.9960692 , 0.83733147, 0.50785093,
       0.89413873, 0.87886018, 0.74508175, 0.48928488, 0.54766891])

In [37]:
vector_t = vector.T
vector_t

array([0.69480758, 0.10481843, 0.9960692 , 0.83733147, 0.50785093,
       0.89413873, 0.87886018, 0.74508175, 0.48928488, 0.54766891])

In [38]:
vector_t.shape

(10,)

При транпонуванні вектор не змінив своєї форми

In [40]:
column_vector = np.expand_dims(vector,axis=1)
column_vector

array([[0.69480758],
       [0.10481843],
       [0.9960692 ],
       [0.83733147],
       [0.50785093],
       [0.89413873],
       [0.87886018],
       [0.74508175],
       [0.48928488],
       [0.54766891]])

In [41]:
column_vector.shape

(10, 1)

In [44]:
column_vector.T

array([[0.69480758, 0.10481843, 0.9960692 , 0.83733147, 0.50785093,
        0.89413873, 0.87886018, 0.74508175, 0.48928488, 0.54766891]])

In [43]:
column_vector.T.shape

(1, 10)